### PR TITLE
Upstream changes

### PR DESCRIPTION
**Pull request by stesee**

### CODE REVIEW

**Comment by ZjzMisaka** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZjzMisaka** [comment]
recheck

**Comment by CoenraadS** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jorgegiro** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jorgegiro** [comment]
recheck

**Comment by JosefPihrt** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by JosefPihrt** [comment]
recheck

**Comment by AmirBosch** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by AmirBosch** [comment]
recheck

**Comment by cjundt** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by twsouthwick** [comment]
Can I get clarification as to why I'm requested here to sign a CLA? I submitted a PR to the main ClosedXML fork, but not sure why I'm being pulled in here. Thanks!

**Comment by stesee** [comment]
> Can I get clarification as to why I'm requested here to sign a CLA? I submitted a PR to the main ClosedXML fork, but not sure why I'm being pulled in here. Thanks!

Sorry for that noise. I did not expect that the bot will request to sign the CLA by all contributors of the main ClosedXML fork. Feel free to ignore the request.

**Comment by cwuethrich** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 0MG-DEN** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request closed without merging**
